title: Sports Data Visualization Blog
description: "Exploring interactive sports analytics and data visualizations using Python tools like Plotly and Bokeh."
author: Austin Rozsa
author_description: "Data enthusiast exploring insights through interactive visualizations in sports analytics."

url: https://aurozsa.github.io
baseurl: /sports_data_visualization
header_image: /assets/img/sports_banner.jpg

social:
    github: aurozsa
    twitter: 
    linkedin: 
    youtube: 

### Advanced Settings
paginate_path: "blog/page:num/"
permalink: /:categories/:year/:month/:day/:title/

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /
    - title: About
      url: /about
